pipeline{
    agent any 

    stages{
        stage('Checkout'){
            checkout scm
        }

        stage('Build Docker Image'){
            steps('Build Docker Image'){
                sh 'docker build -t meghana-resume-build .'
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                docker stop meghna-resume-container || true
                docker rm meghna-resume-container || true
                docker run -d -p 8000:3000 --name meghna-resume-container meghna-resume
                '''
            }
        }
    }

    post{
        success{
            echo 'Pipeline submitted succesfully'
        }

        failure {
            echo 'pipeline failed'
        }
    }
}